name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Ensure this version matches your requirements

    # Step 3: Upgrade pip and install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true  # Prevent pipeline failure if debugging is needed
        pip debug --verbose  # Output detailed dependency resolution logs for debugging

    # Step 4: Run unit tests
    - name: Run Unit Tests
      run: pytest --junitxml=test-results.xml

    # Step 5: Save test results (optional, for CI/CD pipelines using reports)
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results.xml

    # Step 6: Include Debugging Information
    - name: Debug Python Environment
      run: |
        python --version
        pip list

